global:
  scrape_interval: 15s  # Интервал опроса метрик
  evaluation_interval: 15s  # Интервал оценки правил

scrape_configs:




  - job_name: 'mongodb'  # Имя задания для MongoDB
    static_configs:
      - targets: ['mongodb:27017']  # Адрес MongoDB

  - job_name: 'telegram_bot'  # Имя задания для Telegram бота
    static_configs:
      - targets: ['telegram_bot:8000']  # Замените на порт вашего бота

  - job_name: 'consumer'  # Имя задания для Telegram бота
    static_configs:
      - targets: ['consumer:8001']  # Замените на порт вашего бота


  - job_name: 'jmx_exporter'
    static_configs:
      - targets: ['jmxexporter1:5556', 'jmxexporter2:5557', 'jmxexporter3:5558']

