version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./media:/app/media
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

