services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db  # Для постоянного хранения данных

  telegram-bot:
    build: .
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=7972406602:AAF5CLu8uxNtSyoj6Us5lQe4qd3u17YUups
      - MONGODB_URI=mongodb://mongodb:27017/survey_db
    depends_on:
      - mongodb  # Ожидать, пока MongoDB запустится

volumes:
  mongo_data:
